spring:
  application:
    name: ProjetoSpringBoot

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest

      properties:
        spring.json.trusted.packages: br.com.exemplo.projetospringboot.event
  datasource:
    url: jdbc:h2:file:./data/projetodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /ProjetoSpringBoot

jwt:
  secret: "esta-chave-deve-ser-grande-e-secreta-com-pelo-menos-32-bytes"
  expiration: 3600