/*
 Script histórico mantido como referência e atualmente desativado.
 O esquema ativo é administrado pelo Hibernate com ddl-auto.

 Cria a tabela de clientes caso ela ainda não exista.
CREATE TABLE IF NOT EXISTS clientes (
    -- Identificador gerado automaticamente e usado como chave primária.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nome textual do cliente.
    nome VARCHAR(255),
    -- Endereço de e-mail do cliente.
    email VARCHAR(255),
    -- Indica se o cadastro está ativo.
    ativo BOOLEAN
    );

-- Insere um cliente ativo de exemplo.
INSERT INTO clientes (nome, email, ativo)
VALUES ('Carlos', 'carlos@email.com', TRUE);

-- Insere outro cliente ativo de exemplo.
INSERT INTO clientes (nome, email, ativo)
VALUES ('Ana', 'ana@email.com', TRUE);

-- Insere um cliente inativo para cenários de filtro.
INSERT INTO clientes (nome, email, ativo)
VALUES ('Joao', 'joao@email.com', FALSE);

 */
