/*
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    ativo BOOLEAN
    );

INSERT INTO clientes (nome, email, ativo)
VALUES ('Carlos', 'carlos@email.com', TRUE);

INSERT INTO clientes (nome, email, ativo)
VALUES ('Ana', 'ana@email.com', TRUE);

INSERT INTO clientes (nome, email, ativo)
VALUES ('Joao', 'joao@email.com', FALSE);

 */