name: CI - Java e Docker

on:
  push:
    branches:
      - master
      - feature/github

  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6

      - name: Configurar Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Preparar Maven Wrapper
        run: chmod +x mvnw

      - name: Testar e gerar pacote
        run: ./mvnw clean verify

      - name: Construir imagem Docker
        run: docker build --tag projeto-springboot:${{ github.sha }} .